language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: required

install:
    - sudo apt-get update -q
    - sudo apt-get install python3 python3-pip -y
    - sudo pip3 install vim-vint
    - git clone https://github.com/thinca/vim-themis
    - git clone https://github.com/Shougo/unite.vim.git
    - curl -sflL https://github.com/redpen-cc/redpen/releases/download/redpen-1.5.2/redpen-1.5.2.tar.gz -o redpen-1.5.2.tar.gz
    - tar xf redpen-1.5.2.tar.gz
    - export PATH=redpen-distribution-1.5.2/bin:$PATH
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - python3 --version
    - java -version
    - redpen --version
script:
    - vint --color $(git ls-files | grep -e '.vim$' | grep -v vital)
    - ./vim-themis/bin/themis test/
